### ISSUE TITLE
RTL text direction on text field

### ISSUE THREAD

**Issue by Blacksuan19** [4inka/flutter_easy_search_bar#15]
Hello,

I am using this package with arabic text, the direction should be RTL but it is showing LTR as usual. I can't find an option to change from LTR to RTL on the documentation.

there is this package that can automatically change [text direction](https://pub.dev/packages/auto_direction) , is there a way to utilize that package with easy_search_bar?

here's a screenshot of the current behavior

![image](https://user-images.githubusercontent.com/10248473/226394738-aa082f20-828e-4b13-90ab-adcce37141ee.png)

**Comment by dtkdt100** [comment]
until my PR will be merged, you can use my fork: 

```
  easy_search_bar:
    git:
      url: https://github.com/Dolev-Franco/flutter_easy_search_bar.git
      ref: feat/add-text-direction
```
